---
output-format: text
strictness: veryhigh
test-warnings: true
doc-warnings: true

pylint:
  disable:
    - logging-fstring-interpolation
pydocstyle:
  disable:
    - D203
    - D212
    - D213
vulture:
  run: true
bandit:
  run: true
  options:
    config: .bandit.yaml
